### ISSUE TITLE
Useful contributions?

### ISSUE THREAD

**Issue by jeffpaul** [wpdiscussionboard/wp-discussion-board#1]
I'd be happy to open PRs to help add any of the following to the repo:
- [GitHub Action: WordPress.org Plugin Deploy](https://github.com/10up/action-wordpress-plugin-deploy)
- [GitHub Action: WordPress.org Plugin Readme/Assets Update](https://github.com/10up/action-wordpress-plugin-asset-update)
- [GitHub Community file: CODE_OF_CONDUCT.md](https://github.com/10up/.github)
- [GitHub Community file: CONTRIBUTING.md](https://github.com/10up/.github)
- [GitHub Community file: README.md](https://github.com/10up/.github)
- [GitHub Community file: LICENSE.md](https://github.com/10up/.github)
- [Issue Templates](https://github.com/10up/.github)
- [PR Template](https://github.com/10up/.github)

...just let me know and I'd be glad to pitch in!

**Comment by MattGeri** [comment]
Thanks @jeffpaul! I've included slightly modified versions of the templates to the projects and will be looking at implementing the Github actions shortly. Very useful!
